#!/bin/bash

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "main" ]; then
    echo "🔍 Running tests before committing to 'main' branch..."

    pytest test.py --cov=test --cov-report=term-missing > coverage.txt

    if [ $? -eq 0 ]; then
        echo "✅ All tests passed. Proceeding with commit."
        exit 0
    else
        echo "❌ Tests failed. Fix them before committing!"
        exit 1
    fi
fi
